server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:/spring-study/spring-cloud-msa-config
          uri: https://github.com/MARI2020201101/spring-cloud-msa-config.git